import 'package:flutter/material.dart';

class Termsandconditionscreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Terms & Conditions'),
      ),
      body: const Padding(
        padding: EdgeInsets.all(16.0),
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Align(
                alignment: Alignment.topCenter,
                child: Text(
                  'Avatii',
                  style: TextStyle(fontSize: 32, fontWeight: FontWeight.bold),
                ),
              ),
              SizedBox(height: 20),
              // Text(
              //   'Terms and Conditions',
              //   style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
              // ),
              // SizedBox(height: 10),
              // Text(
              //    "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.",
              //   style: TextStyle(fontSize: 16),
              // ),
              Text(
                'Terms and Conditions',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 10),
              Text(
                "Interpretation and Definitions",
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 10),
              Text(
                "Interpretation",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
              ),
              SizedBox(height: 10),
              Text(
                "Definitions",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "For the purposes of this Privacy Policy:",
              ),
              SizedBox(height: 5),
              Text(
                "• Account means a unique account created for You to access our Service or parts of our Service.",
              ),
              Text(
                "• Affiliate means an entity that controls, is controlled by or is under common control with a party, where 'control' means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.",
              ),
              Text(
                "• Application refers to Avatii, the software program provided by the Company.",
              ),
              Text(
                "• Company (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to Avatii.",
              ),
              Text(
                "• Country refers to: Jammu and Kashmir, India.",
              ),
              Text(
                "• Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
              ),
              Text(
                "• Personal Data is any information that relates to an identified or identifiable individual.",
              ),
              Text(
                "• Service refers to the Application.",
              ),
              Text(
                "• Service Provider means any natural or legal person who processes the data on behalf of the Company.",
              ),
              Text(
                "• Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
              ),
              Text(
                "• You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
              ),
              SizedBox(height: 20),
              Text(
                "Collecting and Using Your Personal Data",
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 10),
              Text(
                "Types of Data Collected",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "Personal Data",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
              ),
              Text("• First name and last name"),
              Text("• Phone number"),
              Text("• Address, State, Province, ZIP/Postal code, City"),
              SizedBox(height: 10),
              Text(
                "Usage Data",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "Usage Data is collected automatically when using the Service.",
              ),
              Text(
                "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
              ),
              Text(
                "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
              ),
              Text(
                "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.",
              ),
              SizedBox(height: 20),
              Text(
                "Use of Your Personal Data",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "The Company may use Personal Data for the following purposes:",
              ),
              Text("• To provide and maintain our Service"),
              Text(
                "• To manage Your Account: to manage Your registration as a user of the Service.",
              ),
              Text(
                "• For the performance of a contract: to develop, comply with, and undertake a purchase contract for products, items, or services.",
              ),
              Text(
                "• To contact You: to contact You by email, phone calls, SMS, or other equivalent forms of electronic communication.",
              ),
              Text(
                "• To manage Your requests: to attend and manage Your requests to Us.",
              ),
              Text(
                "• For business transfers: to evaluate or conduct a merger, sale of assets, financing, or acquisition.",
              ),
              Text(
                "• For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, and improving our Service.",
              ),
              SizedBox(height: 20),
              Text(
                "Retention of Your Personal Data",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.",
              ),
              SizedBox(height: 20),
              Text(
                "Disclosure of Your Personal Data",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "We may disclose Your Personal Data in the following situations:",
              ),
              Text(
                "• For business transactions: We may disclose Your Personal Data in connection with a merger, sale, or asset transfer.",
              ),
              Text(
                "• With Service Providers: We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service.",
              ),
              Text(
                "• For law enforcement: Under certain circumstances, the Company may be required to disclose Your Personal Data by law or in response to valid requests by public authorities.",
              ),
              SizedBox(height: 20),
              Text(
                "Security of Your Personal Data",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure.",
              ),
              SizedBox(height: 20),
              Text(
                "Children's Privacy",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.",
              ),
              SizedBox(height: 20),
              Text(
                "Changes to this Privacy Policy",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.",
              ),
              SizedBox(height: 20),
              Text(
                "Contact Us",
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 5),
              Text(
                "If you have any questions about this Privacy Policy, You can contact us:",
              ),
              SizedBox(height: 5),
              Text(
                "• By email: avatiiavatii@gmail.com",
              ),
              SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }
}
